### ISSUE TITLE
Enable students to install and run existing app

### ISSUE THREAD

**Issue by davclark** [BIDS-collaborative/brainspell#6]
@jbpoline is likely in the lead on this as of "right now," though I've talked about making a simple ansible script, given the lack of provisioning scripts at the moment.

As it stands, we think we have reasonable instructions in the Wiki for getting apache configured. MySql still needs to be set up, and the stock Ubuntu instructions don't seem to work for setting the root password, which is a pre-req for other things working (like phpmyadmin).

I very much prefers to use ansible in situations like this. I expect there to be a lot of errors that take time to track down as beginners go about setting up the project.

**Comment by jbpoline** [comment]
Hi, 
An ansible configuration would be awesome if feasable.  I have phpmyadmin running but I get into trouble when trying to load the brainspell.sql DB.   I manage to change the defaults so that it can load 64M of data, but get the  '#1046 - No database selected ' error, which persits even if I create a 'brainspell' DB,  try to USE it, and then SOURCE the brainspell.sql file  ... will invesitgate more. 

Error

## SQL query:

## -- Database: `brainspell`

---

## 

## -- Table structure for table `Articles`

CREATE TABLE IF NOT EXISTS `Articles` (
`UniqueID` int( 25 ) NOT NULL AUTO_INCREMENT ,
`TIMESTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ,
`Title` text CHARACTER SET utf8 COLLATE utf8_bin NOT NULL ,
`Authors` text CHARACTER SET utf8 COLLATE utf8_bin NOT NULL ,
`Abstract` text CHARACTER SET utf8 COLLATE utf8_bin NOT NULL ,
`Reference` text CHARACTER SET utf8 COLLATE utf8_bin NOT NULL ,
`PMID` varchar( 64 ) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL ,
`DOI` varchar( 128 ) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL ,
`NeuroSynthID` varchar( 64 ) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL ,
`Experiments` text CHARACTER SET utf8 COLLATE utf8_bin NOT NULL ,
`Metadata` text CHARACTER SET utf8 COLLATE utf8_bin NOT NULL ,
PRIMARY KEY ( `UniqueID` )
) ENGINE = InnoDB DEFAULT CHARSET = latin1 AUTO_INCREMENT =12512;

MySQL said: Documentation
#1046 - No database selected

**Comment by jbpoline** [comment]
this issue was resoved with the appropriate setting for phpmyadmin (choose Collation: `latin1_swedish_ci`) - full instructions are in the repo now
